export const FETCH_TAKEN_BOOKS_REQUEST: string = 'FETCH_TAKEN_BOOKS_REQUEST';
export const FETCH_TAKEN_BOOKS_SUCCESS: string = 'FETCH_TAKEN_BOOKS_SUCCESS';
export const FETCH_TAKEN_BOOKS_FAILURE: string = 'FETCH_TAKEN_BOOKS_FAILURE';