export const FETCH_ABOUTUS_REQUEST: string = "FETCH_ABOUTUS_REQUEST";
export const FETCH_ABOUTUS_GENERAL_SUCCESS: string = "FETCH_ABOUTUS_GENERAL_SUCCESS";
export const FETCH_ABOUTUS_CHILDREN_SUCCESS: string = "FETCH_ABOUTUS_CHILDREN_SUCCESS";
export const FETCH_ABOUTUS_FAILURE: string = "FETCH_ABOUTUS_FAILURE";