export const FETCH_BOOKS_REQUEST: string = 'FETCH_BOOKS_REQUEST';
export const FETCH_BOOKS_SUCCESS: string = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE: string = 'FETCH_BOOKS_FAILURE';
export const ADD_BOOK_CATEGORY: string = 'ADD_BOOK_CATEGORY';
export const FETCH_BOOK_CATEGORYS: string = 'FETCH_BOOK_CATEGORYS';